# micro_gvl_cmd_apps.yml

# This script will install all of the command line tools for the mGVL including Mauve, IGV, Artemis and the nullarbor suite of programs. (Nullarbor, Prokka, Snippy, etc.)

# Start by making sure that the directory /mnt/gvl/apps exists..

- name: Check gvl_apps directory exists
  file: name="{{ gvl_app_path }}" state=directory owner=ubuntu group=ubuntu
  sudo: yes
  sudo_user: root

#Include statements for the other tools. Starting with linux brew
- include: install_linuxbrew.yml
  environment:
    PATH: "{{ gvl_app_path }}/linuxbrew/bin:{{ ansible_env.PATH }}"
    MANPATH: "{{ gvl_app_path }}/linuxbrew/share/man:{{ ansible_env.MANPATH }}"
    INFOPATH: "{{ gvl_app_path }}/linuxbrew/share/info:{{ ansible_env.INFOPATH }}"
    HOMEBREW_TEMP: "/mnt/transient_nfs/homebrew_temp"
    HOMEBREW_CACHE: "/mnt/transient_nfs/homebrew_cache"
    TEMPDIR: "/mnt/transient_nfs"
    TEMP: "/mnt/transient_nfs"

#Install nullarbor and associated packages via brew
- include: install_nullarbor.yml
  environment: "{{ linuxbrew_env }}"
